name: Build Windows

on: [push]

env:
  KIVY_GL_BACKEND: angle_sdl2
  # https://github.com/Alb-310/Geogramint/issues/8#issuecomment-1366548008

jobs:
  Build-Windows:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install pip packages - macos
        run: pip install -r build_requirements/pip_requirements-macos.txt
      - name: install pip packages - kivy
        run: pip install -r build_requirements/pip_requirements.txt

      - name: copy spec file
        run: copy build_requirements/ImgSplitter-macos-onefile.spec.src ImgSplitter.spec

      - name: build spec
        run: python -m PyInstaller ImgSplitter.spec

      - name: Archive Manager Build
        uses: actions/upload-artifact@v4
        with:
          name: build-macos
          path: build

      - name: Create DMG File
        run:
          pushd dist
          hdiutil create ./ImgSplitter.dmg -srcfolder ImgSplitter.app -ov
          popd

      - name: Archive Manager dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos
          path: dist
